flask-adminlte-scaffold-master/app/models.py
# -*- coding: utf-8 -*-

from peewee import MySQLDatabase, Model, CharField, BooleanField, IntegerField
import json
from werkzeug.security import check_password_hash
from flask_login import UserMixin
from app import login_manager
from conf.config import config
import os

cfg = config[os.getenv('FLASK_CONFIG') or 'default']

db = MySQLDatabase(host=cfg.DB_HOST, user=cfg.DB_USER, passwd=cfg.DB_PASSWD, database=cfg.DB_DATABASE)


class BaseModel(Model):
    class Meta:
        database = db

    def __str__(self):
        r = {}
        for k in self._data.keys():
            try:
                r[k] = str(getattr(self, k))
            except:
                r[k] = json.dumps(getattr(self, k))
        # return str(r)
        return json.dumps(r, ensure_ascii=False)


# 管理员工号
class User(UserMixin, BaseModel):
    username = CharField()  # 用户名
    password = CharField()  # 密码
    fullname = CharField()  # 真实性名
    email = CharField()  # 邮箱
    phone = CharField()  # 电话
    status = BooleanField(default=True)  # 生效失效标识

    def verify_password(self, raw_password):
        return check_password_hash(self.password, raw_password)


# 通知人配置
class CfgNotify(BaseModel):
    check_order = IntegerField()  # 排序
    notify_type = CharField()  # 通知类型：MAIL/SMS
    notify_name = CharField()  # 通知人姓名
    notify_number = CharField()  # 通知号码
    status = BooleanField(default=True)  # 生效失效标识


@login_manager.user_loader
def load_user(user_id):
    return User.get(User.id == int(user_id))


# 建表
def create_table():
    db.connect()
    db.create_tables([CfgNotify, User])


if __name__ == '__main__':
    create_table()

flask-adminlte-scaffold-master/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, PasswordField, SelectField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo


class CfgNotifyForm(FlaskForm):
    check_order = StringField('排序', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    notify_type = SelectField('通知类型', choices=[('MAIL', '邮件通知'), ('SMS', '短信通知')],
                              validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    notify_name = StringField('通知人姓名', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    notify_number = StringField('通知号码', validators=[DataRequired(message='不能为空'), Length(0, 64, message='长度不正确')])
    status = BooleanField('生效标识', default=True)
    submit = SubmitField('提交')

flask-adminlte-scaffold-master/app/__init__.py
from flask import Flask
from flask_login import LoginManager
from conf.config import config
import logging
from logging.config import fileConfig
import os

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
fileConfig('conf/log-app.conf')

def get_logger(name):
    return logging.getLogger(name)


def get_basedir():
    return os.path.abspath(os.path.dirname(__file__))


def get_config():
    return config[os.getenv('FLASK_CONFIG') or 'default']


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

flask-adminlte-scaffold-master/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms, errors

flask-adminlte-scaffold-master/app/main/views.py
from app import get_logger, get_config
import math
from flask import render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from app import utils
from app.models import CfgNotify
from app.main.forms import CfgNotifyForm
from . import main

logger = get_logger(__name__)
cfg = get_config()

# 通用列表查询
def common_list(DynamicModel, view):
    # 接收参数
    action = request.args.get('action')
    id = request.args.get('id')
    page = int(request.args.get('page')) if request.args.get('page') else 1
    length = int(request.args.get('length')) if request.args.get('length') else cfg.ITEMS_PER_PAGE

    # 删除操作
    if action == 'del' and id:
        try:
            DynamicModel.get(DynamicModel.id == id).delete_instance()
            flash('删除成功')
        except:
            flash('删除失败')

    # 查询列表
    query = DynamicModel.select()
    total_count = query.count()

    # 处理分页
    if page: query = query.paginate(page, length)

    dict = {'content': utils.query_to_list(query), 'total_count': total_count,
            'total_page': math.ceil(total_count / length), 'page': page, 'length': length}
    return render_template(view, form=dict, current_user=current_user)


# 通用单模型查询&新增&修改
def common_edit(DynamicModel, form, view):
    id = request.args.get('id', '')
    if id:
        # 查询
        model = DynamicModel.get(DynamicModel.id == id)
        if request.method == 'GET':
            utils.model_to_form(model, form)
        # 修改
        if request.method == 'POST':
            if form.validate_on_submit():
                utils.form_to_model(form, model)
                model.save()
                flash('修改成功')
            else:
                utils.flash_errors(form)
    else:
        # 新增
        if form.validate_on_submit():
            model = DynamicModel()
            utils.form_to_model(form, model)
            model.save()
            flash('保存成功')
        else:
            utils.flash_errors(form)
    return render_template(view, form=form, current_user=current_user)


# 根目录跳转
@main.route('/', methods=['GET'])
@login_required
def root():
    return redirect(url_for('main.index'))


# 首页
@main.route('/index', methods=['GET'])
@login_required
def index():
    return render_template('index.html', current_user=current_user)


# 通知方式查询
@main.route('/notifylist', methods=['GET', 'POST'])
@login_required
def notifylist():
    return common_list(CfgNotify, 'notifylist.html')


# 通知方式配置
@main.route('/notifyedit', methods=['GET', 'POST'])
@login_required
def notifyedit():
    return common_edit(CfgNotify, CfgNotifyForm(), 'notifyedit.html')

flask-adminlte-scaffold-master/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% block head %}{% endblock %}
    <title>管理平台 | {% block title %}标题{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/ionicons/css/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-slider/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/pace/pace.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/bootstrap-switch/bootstrap-switch.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/select2/select2.min.css') }}">
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/adminlte/css/AdminLTE.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='plugins/adminlte/css/skins/skin-blue.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css') }}">
    <!--[if lt IE 9]>
    <script src="plugins/html5shiv.min.js"></script>
    <script src="plugins/respond.min.js"></script>
    <![endif]-->
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!--头部-->
    <header class="main-header">
        <a href="{{ url_for('main.index') }}" class="logo">
            <span class="logo-mini"><b>N</b></span>
            <span class="logo-lg"><b>管理平台</b></span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ url_for('static', filename='images/avatar.jpg') }}" class="user-image"
                                 alt="User Image">
                            <span class="hidden-xs">{{current_user.username}}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{{ url_for('static', filename='images/avatar.jpg') }}"
                                     class="img-circle" alt="User Image">
                                <p>
                                    <span>{{current_user.fullname}}</span>
                                    <small>{{current_user.email}}</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{{ url_for('main.index') }}" class="btn btn-default btn-flat">统计信息</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{{ url_for('auth.logout') }}" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!--侧边栏-->
    <aside class="main-sidebar">
        <section class="sidebar">
            <ul class="sidebar-menu">
                <li class="header">功能导航</li>
                <li>
                    <a href="{{ url_for('main.index') }}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-user"></i>
                        <span>XX管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url_for('main.notifyedit') }}"><i class="fa fa-circle-o"></i> 编辑</a></li>
                        <li><a href="{{ url_for('main.notifylist') }}"><i class="fa fa-circle-o"></i> 查询</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-bug"></i>
                        <span>XX管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url_for('main.notifyedit') }}"><i class="fa fa-circle-o"></i> 编辑</a></li>
                        <li><a href="{{ url_for('main.notifylist') }}"><i class="fa fa-circle-o"></i> 查询</a></li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-send"></i>
                        <span>XX管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url_for('main.notifyedit') }}"><i class="fa fa-circle-o"></i> 编辑</a></li>
                        <li><a href="{{ url_for('main.notifylist') }}"><i class="fa fa-circle-o"></i> 查询</a></li>
                    </ul>
                </li>

                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-cog"></i>
                        <span>XX管理</span>
                        <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{{ url_for('main.notifyedit') }}"><i class="fa fa-circle-o"></i> 功能点</a></li>
                        <li><a href="{{ url_for('main.notifylist') }}"><i class="fa fa-circle-o"></i> 功能点</a></li>
                    </ul>
                </li>
            </ul>
        </section>
    </aside>

    <div class="content-wrapper">
        <!--导航栏-->
        {% block navbar %}{% endblock %}
        <!--正文-->
        <section class="content">
            {% block content %}{% endblock %}

        </section>
    </div>
    <!--页脚-->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>版本号</b> 1.0.0
        </div>
        Copyright &copy; 2017 <a href="http://www.si-tech.com.cn">XXXX公司</a>
    </footer>
    <!--模态窗口-->
    <div class="modal-wrapper">
        <div id="alert-modal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <!--<button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
                        <!--<span aria-hidden="true">&times;</span></button>-->
                        <h4 class="modal-title">提示</h4>
                    </div>
                    <div class="modal-body">
                        提示内容
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left btn-no" data-dismiss="modal">取消</button>
                        <button type="button" class="btn btn-default btn-yes" data-dismiss="modal">确定</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap-slider/bootstrap-slider.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/pace/pace.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/bootstrap-switch/bootstrap-switch.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/select2/select2.full.min.js') }}"></script>
<script src="{{ url_for('static', filename='plugins/adminlte/js/app.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/global.js') }}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

flask-adminlte-scaffold-master/app/templates/index.html
{% extends "base.html" %}

{% block title %}首页{% endblock %}

{% block navbar %}
<section class="content-header">
    <h1>首页</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">首页</li>
    </ol>
</section>
{% endblock %}

{% block content %}
<div class="box box-primary">
    <div class="box-body">
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3 id="count01">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-ios-gear-outline"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3 id="count02">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-iphone"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3 id="count03">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3 id="count04">0</h3>
                        <p>统计信息</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-info"></i> 温馨提示</h4>
            <ol>
                <li>温馨提示温馨提示温馨提示</li>
                <li>温馨提示温馨提示温馨提示</li>
            </ol>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        var jsInObj = null;
        restTemplate("GET", "/stats/summary", jsInObj, function (jsOutObj) {
            $("#count01").text(jsOutObj.batch_count);
            $("#count02").text(jsOutObj.test_count);
            $("#count03").text(jsOutObj.succ_count);
            $("#count04").text(jsOutObj.fail_count);
        });
    }
</script>
{% endblock %}

flask-adminlte-scaffold-master/app/templates/message.html
{% if get_flashed_messages() %}
<div class="alert callout callout-info" id="alertarea">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <h4><i class="icon fa fa-info"></i>提示信息</h4>
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

flask-adminlte-scaffold-master/app/templates/notifyedit.html
{% extends "base.html" %}

{% block title %}通知方式配置{% endblock %}


{% block navbar %}
<section class="content-header">
    <h1>通知方式配置</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">通知方式管理</li>
        <li class="active">通知方式配置</li>
    </ol>
</section>
{% endblock %}


{% block content %}
<div class="box box-primary">
    <form method="post">
        {{form.hidden_tag()}}
        <div class="box-header with-border">
            {% include 'message.html' %}
        </div>

        <div class="box-body">
            <div class="col-md-12">
                <div class="form-group">
                    <label>{{form.check_order.label}}</label>
                    {{form.check_order(class_="slider form-control",placeholder="请输入 列表顺序")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.notify_type.label}}</label>
                    {{form.notify_type(class_="form-control select2",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.notify_name.label}}</label>
                    {{form.notify_name(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>{{form.notify_number.label}}</label>
                    {{form.notify_number(class_="form-control",placeholder="请输入")}}
                </div>
            </div>
        </div>

        <div class="box-footer">
            <div class="col-md-12">
                {{form.status()}}
                {{form.submit(class_="btn btn-primary pull-right")}}
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        slide_value = $(".slider").val() == "" ? 50 : parseInt($(".slider").val());
        $(".slider").slider({
            id: "blue",
            max: 100,
            value: slide_value
        });

        switch_value = $('#status')[0].checked
        $('#status').bootstrapSwitch({
            state: switch_value,
            onText: '生效',
            offText: '失效'

        });

        $(".select2").select2();
    }
</script>
{% endblock %}

flask-adminlte-scaffold-master/app/templates/notifylist.html
{% extends "base.html" %}

{% block title %}通知方式查询{% endblock %}
{% block navbar %}
<section class="content-header">
    <h1>通知方式查询</h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> 当前位置</li>
        <li class="active">通知方式管理</li>
        <li class="active">通知方式查询</li>
    </ol>
</section>
{% endblock %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        {% include 'message.html' %}
    </div>

    <div class="box-body">
        {% if form%}
        <table class="table table-bordered">
            <tr>
                <th>ID</th>
                <th>通知方式</th>
                <th>通知人姓名</th>
                <th>通知人号码</th>
                <th>状态</th>
                <th>编辑</th>
                <th>删除</th>
            </tr>
            {% for row in form.content %}
            <tr>
                <td>{{row.id}}</td>
                <td>{{row.notify_type}}</td>
                <td>{{row.notify_name}}</td>
                <td>{{row.notify_number}}</td>
                <td>
                    {% if row.status %}
                    <input type="checkbox" data-id="{{row.id}}" class="status" data-on-text="生效" data-off-text="失效"
                           data-size="mini" checked>
                    {% else %}
                    <input type="checkbox" data-id="{{row.id}}" class="status" data-on-text="生效" data-off-text="失效"
                           data-size="mini">
                    {% endif %}
                </td>
                <td><a class='fa fa-lg fa-edit text-light-blue'
                       href='{{ url_for("main.notifyedit", id=row.id) }}'></a></td>
                <td><a class='fa fa-lg fa-warning text-red' href='?action=del&id={{row.id}}'></a></td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>

    <div class="box-footer clearfix">
        {% if form%}
        <ul class="pagination pagination-sm no-margin pull-right">
            <li><a href="#">&laquo;</a></li>
            {% for i in range(1, form.total_page+ 1) %}
            {% if i == form.page %}
            <li><a href="?page={{i}}"><b>{{i}}</b></a></li>
            {% else %}
            <li><a href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            <li><a href="#">&raquo;</a></li>
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function initPage() {
        slide_value = $(".slider").val() == "" ? 50 : parseInt($(".slider").val());
        $(".slider").slider({
            id: "blue",
            max: 100,
            value: slide_value
        });

        $('.status').bootstrapSwitch();
        $(".status").on("switchChange.bootstrapSwitch", function (event, state) {
            switchStatus($(this).data("id"), state, this);
        });
    }
    function switchStatus(id, status, switchBox) {
        restTemplate("PUT", "/notifies/" + id + "/status/" + status, null, function () {
            $($(switchBox)).bootstrapSwitch("state", status);
        });
    }
</script>
{% endblock %}